name: Cache CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup cache
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-6016777

      - name: prime-cache-6016777
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
